name: sphinx-autogenerator

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    # Standard drop-in approach that should work for most people.
    - uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "docs/"
    # Great extra actions to compose with:
    # Create an artifact of the html output.
    - uses: actions/upload-artifact@v1
      with:
        name: DocumentationHTML
        path: docs/_build/html/
    - name: setup git config
      run: |
          # setup the username and email. I tend to use 'GitHub Actions Bot' with no email by default
          git config user.name "gowtham-sathyan"
          git config user.email "gowthamsathyan@gmail.com"

    - name: commit
      run: |
          # Stage the file, commit and push
          git add .
          git commit -m "Updated documentation"
          git push
    # ===============================
