name: sphinx-autogenerator

on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    # Standard drop-in approach that should work for most people.
    - uses: ammaraskar/sphinx-action@master
      with:
        build-command: "make html"
        docs-folder: "docs/"
    # Great extra actions to compose with:
    # Create an artifact of the html output.
    - uses: actions/upload-artifact@v1
      with:
        name: DocumentationHTML
        path: docs/_build/html/
    - uses: actions/checkout@v2
    - name: setup git config and commit
      run: |
          git clone https://github.com/ekanshsinghal/se-hw2-fall22.git
          rm -rf se-hw2-fall22/docs/_build/html/*
          cp -r docs/_build/html/* se-hw2-fall22/docs/_build/html/
          cd se-hw2-fall22
          git config --global user.name "gowtham-sathyan"
          git config --global user.email "gowthamsathyan@gmail.com"
          git add .
          git commit -m "Updated documentation" -a || true
          git push
    # ===============================
